---
- hosts: localhost
  become: yes # This means that all tasks will be executed with sudo
  tasks:
   - name: Add sdn user
     user:
      name: sdn
      comment: "devstack installar sudo user"      
     when:
        - ansible_distribution == "Ubuntu"       
        - ansible_os_family == "Debian"
   - name: Update repositories cache and install `software-properties-common` package
     apt:
      name: software-properties-common
      update_cache: yes     
     when:
        - ansible_distribution == "Ubuntu"       
        - ansible_os_family == "Debian"
   - name: Add Oracle Java 1.8 repos 
     command: add-apt-repository ppa:webupd8team/java 
     when:
        - ansible_distribution == "Ubuntu"       
        - ansible_os_family == "Debian"
   # - name: Add the Jenkins repository to the yum repos
     # command: wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
     # when:
        # - ansible_distribution == "Scientific"       
        # - ansible_os_family == "RedHat"
   - name: Run the equivalent of "apt-get update" as a separate step
     apt:
        update_cache: yes
     when:
        - ansible_distribution == "Ubuntu"       
        - ansible_os_family == "Debian"        
   - name: Execute the command in remote shell; Install Oracle Java 1.8
     shell: /vagrant/somescript.sh
   # - name:  Install Oracle Java 1.8 
     # command: echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" 
     # when:
        # - ansible_distribution == "Ubuntu"       
        # - ansible_os_family == "Debian"        
   # - name:  Install Oracle Java 1.8 
     # command: debconf-set-selections 
     # when:
        # - ansible_distribution == "Ubuntu"       
        # - ansible_os_family == "Debian"        
   - name: Install Oracle Java 1.8  
     apt: name={{item}} state=latest
     with_items:
       - oracle-java8-installer 
       - oracle-java8-set-default
       - curl
     when:     
        - ansible_distribution == "Ubuntu"       
        - ansible_os_family == "Debian"        
   - name: Download ONOS Magpie 1.12.0
     command: wget -c http://repo1.maven.org/maven2/org/onosproject/onos-releases/onos-1.12.0/onos-1.12.0.tar.gz
     args:
        chdir: /opt/     
     when:
        - ansible_distribution == "Ubuntu"       
        - ansible_os_family == "Debian"
   - name: Untar the ONOS archive into /opt
     command: tar xzf onos-1.12.0.tar.gz
     args:
        chdir: /opt/     
     when:
        - ansible_distribution == "Ubuntu"       
        - ansible_os_family == "Debian"        
   - name: Rename the extracted directory to "onos"
     command: mv onos-1.12.0 onos
     args:
        chdir: /opt/     
     when:
        - ansible_distribution == "Ubuntu"       
        - ansible_os_family == "Debian"        
        
        
   - name: Disable the firewall 
     systemd:
      name:  firewalld
      state: stopped
     when:
        - ansible_distribution == "Scientific"       
        - ansible_os_family == "RedHat"
   - name: Add the Jenkins repository to the yum repos.Installation of a stable version.LTS YUM repository 
     get_url:
      url:  http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
      mode: 644
     when:
        - ansible_distribution == "Scientific"       
        - ansible_os_family == "RedHat"
   - name: Receive repo keys hkp://pool.sks-keyservers.net:80 
     command: rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
     when:     
        - ansible_distribution == "Scientific"       
        - ansible_os_family == "RedHat"
   - name: Install packages java,jenkins 
     yum: name={{item}} state=latest
     with_items:
       - java-1.8.0-openjdk 
       - jenkins
     when:     
        - ansible_distribution == "Scientific"       
        - ansible_os_family == "RedHat"