---
- hosts: localhost
  become: yes #  all tasks will be executed with sudo
  tasks:
   - name: Add sdn user
     user:
      name: sdn
      comment: "devstack installar sudo user"
     when:
        - ansible_distribution == "Ubuntu"
        - ansible_os_family == "Debian"
   - name: Update repositories cache and install `software-properties-common` package
     apt:
      name: software-properties-common
      update_cache: yes
     when:
        - ansible_distribution == "Ubuntu"
        - ansible_os_family == "Debian"
   - name: Add Oracle Java 1.8 repos
     command: add-apt-repository ppa:webupd8team/java
     when:
        - ansible_distribution == "Ubuntu"
        - ansible_os_family == "Debian"
   - name: Run the equivalent of "apt-get update" as a separate step
     apt:
        update_cache: yes
     when:
        - ansible_distribution == "Ubuntu"
        - ansible_os_family == "Debian"
   - name: Execute the command in remote shell; Install Oracle Java 1.8
     shell: /vagrant/somescript.sh
   - name: Install Oracle Java 1.8
     apt: name={{item}} state=latest
     with_items:
       - oracle-java8-installer
       - oracle-java8-set-default
       - curl
     when:
        - ansible_distribution == "Ubuntu"
        - ansible_os_family == "Debian"
   - name: Download ONOS Magpie 1.12.0
     command: wget -c http://repo1.maven.org/maven2/org/onosproject/onos-releases/onos-1.12.0/onos-1.12.0.tar.gz
     args:
        chdir: /opt/
     when:
        - ansible_distribution == "Ubuntu"
        - ansible_os_family == "Debian"
   - name: Untar the ONOS archive into /opt
     command: tar xzf onos-1.12.0.tar.gz
     args:
        chdir: /opt/
     when:
        - ansible_distribution == "Ubuntu"
        - ansible_os_family == "Debian"
   - name: Rename the extracted directory to "onos"
     command: mv onos-1.12.0 onos
     args:
        chdir: /opt/
     when:
        - ansible_distribution == "Ubuntu"
        - ansible_os_family == "Debian"


   - name: Disable the firewall
     systemd:
      name:  ufw
      state: stopped
     when:
        - ansible_distribution == "Ubuntu"
        - ansible_os_family == "Debian"
