# -*- mode: ruby -*-
# vi: set ft=ruby :

# https://wiki.onosproject.org/display/ONOS/Requirements
# the following minimum requirements should be satisfied:
# 2 core CPU
# 2 GB RAM
# 10 GB hdd
# 1 NIC (any speed)

# Ports:
# ONOS requires the following ports to be open, in order to make the corresponding functionalities available:
# 8181    for REST API and GUI
# 8101    to access the ONOS CLI
# 9876    for intra-cluster communication (communication between target machines)
# 6653    optional, for OpenFlow
# 6640    optional, for OVSDB


Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "512"
    vb.cpus = 1
  end

  config.vm.define "onos01" do |webtier|
    # webtier.vm.box = "bento/ubuntu-16.04" #OK
    webtier.vm.box = "bento/ubuntu-18.10" #OK
    webtier.vm.hostname = "onos01"
    webtier.vm.network "private_network", ip: "192.168.45.10"
    webtier.vm.network "forwarded_port", guest: 8181, host: 8181
    webtier.vm.provider "virtualbox" do |vb|
        vb.name = "onos01"
        vb.memory = "2048"
    end
    webtier.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "deploy.yml"
    ansible.become = true
    ansible.version = "2.8.1"
    end
    webtier.vm.provision "shell", inline: <<-SHELL
          echo "==============================================================================================="
          echo "================================   openjdk/openjre mininet onos      =========================="
          echo "==============================================================================================="
          sudo apt-get update
          sudo apt-get install -y --quiet default-jre mininet curl  # try default openjre
          # sudo apt-get install -y --quiet default-jdk mininet curl # try default openjdk
          ONOS_VERSION=2.1.0
          URL_DL=http://repo1.maven.org/maven2/org/onosproject/onos-releases/$ONOS_VERSION/onos-$ONOS_VERSION.tar.gz
          cd /opt && sudo wget --quiet $URL_DL
          sudo tar xzf onos-$ONOS_VERSION.tar.gz
          sudo adduser sdn --system --group
          sudo mv onos-$ONOS_VERSION onos && sudo chown -R sdn:sdn onos
          # sudo /opt/onos/bin/onos-service start # without service
          sudo cp /opt/onos/init/onos.initd /etc/init.d/onos
          sudo cp /opt/onos/init/onos.service /etc/systemd/system/
          sudo systemctl daemon-reload
          sudo systemctl enable onos && sudo systemctl start onos
          sudo systemctl status onos
    SHELL
    end



end
