# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "512"
    vb.cpus = 1
  end

    config.vm.define "onos01" do |webtier|
      # webtier.vm.box = "bento/ubuntu-16.04" # OK
      webtier.vm.box = "bento/ubuntu-18.10"
      webtier.vm.hostname = "onos01"
      webtier.vm.network "private_network", ip: "192.168.45.11"
      webtier.vm.network "forwarded_port", guest: 8181, host: 8181
      webtier.vm.provider "virtualbox" do |vb|
          vb.name = "onos01"
          vb.memory = "2048"
      end
      webtier.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "deploy.yml"
      ansible.become = true
      ansible.version = "2.8.1"
      end
      webtier.vm.provision "shell", inline: <<-SHELL
            echo "==============================================================================================="
            echo "================================    INSTALL DOCKER       ======================================"
            echo "==============================================================================================="
            sudo apt-get update
            sudo apt-get remove docker docker-engine docker.io
            sudo apt-get install apt-transport-https ca-certificates curl software-properties-common -y
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo apt-key fingerprint 0EBFCD88
            sudo add-apt-repository \
            "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) \
            stable"
            sudo apt-get update
            sudo apt-get install docker-ce -y
            sudo docker --version
            echo "==============================================================================================="
            echo "================================    INSTALL MININET       ======================================"
            echo "==============================================================================================="
            sudo apt-get install -y mininet
            echo "==============================================================================================="
            echo "================================    INSTALL ONOS         ======================================"
            echo "==============================================================================================="
            # sudo docker run -p 8181:8181 -it -d --name simple-onos onosproject/onos:latest
            sudo docker run -p 8181:8181 -it -d --name simple-onos onosproject/onos:2.1.0
            echo "onos01 up && running"
      SHELL
      end

end
